// <auto-generated />
using System;
using Chatman.Persistence.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Chatman.Api.Migrations
{
    [DbContext(typeof(ChatmanContext))]
    [Migration("20190409145932_Initial-Update")]
    partial class InitialUpdate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.ConversationBlockedUsers", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConversationId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("BlockedUsers");
                });

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.ConversationDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("OwnerId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("OwnerId")
                        .IsUnique();

                    b.ToTable("Conversations");
                });

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.ConversationUsersParticipating", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConversationId");

                    b.Property<string>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("UserId");

                    b.ToTable("ConversationUsersParticipating");
                });

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.MessageDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConversationId");

                    b.Property<DateTime>("Date");

                    b.Property<string>("SenderId");

                    b.Property<string>("Text");

                    b.HasKey("Id");

                    b.HasIndex("ConversationId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.UserDto", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Username")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.ConversationBlockedUsers", b =>
                {
                    b.HasOne("Chatman.Persistence.EF.Dtos.ConversationDto", "Conversation")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("ConversationId");

                    b.HasOne("Chatman.Persistence.EF.Dtos.UserDto", "User")
                        .WithMany("BlockedUsers")
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.ConversationDto", b =>
                {
                    b.HasOne("Chatman.Persistence.EF.Dtos.UserDto", "Owner")
                        .WithOne("Conversation")
                        .HasForeignKey("Chatman.Persistence.EF.Dtos.ConversationDto", "OwnerId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.ConversationUsersParticipating", b =>
                {
                    b.HasOne("Chatman.Persistence.EF.Dtos.ConversationDto", "Conversation")
                        .WithMany("UsersParticipating")
                        .HasForeignKey("ConversationId");

                    b.HasOne("Chatman.Persistence.EF.Dtos.UserDto", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("Chatman.Persistence.EF.Dtos.MessageDto", b =>
                {
                    b.HasOne("Chatman.Persistence.EF.Dtos.ConversationDto", "Conversation")
                        .WithMany()
                        .HasForeignKey("ConversationId");
                });
#pragma warning restore 612, 618
        }
    }
}
